services:
    mysql:
        # platform: linux/x86_64
        container_name: mysql
        restart: unless-stopped
        image: mysql:8.0
        tty: true
        environment:
            MYSQL_DATABASE: ${MYSQL_DB_NAME}
            MYSQL_USER: ${MYSQL_DB_USER}
            MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASSWORD}
        volumes:
            - ./data/mysql/data:/var/lib/mysql
            - ./data/mysql/my.cnf:/etc/mysql/my.cnf
        ports:
            - '${MYSQL_DB_PORT}:3306'
        networks:
            - main-network

    postgres:
        container_name: postgres
        restart: unless-stopped
        image: postgres:13
        tty: true
        environment:
            DATABASE_HOST: ${POSTGRES_DB_HOST}
            DATABASE_PORT: ${POSTGRES_DB_PORT}
            POSTGRES_DB: ${POSTGRES_DB_NAME}
            POSTGRES_USER: ${POSTGRES_DB_USER}
            POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
        volumes:
            - ./data/postgres/data:/var/lib/postgresql/data
            - ./data/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
        ports:
            - '${POSTGRES_DB_PORT}:5432'
        networks:
            - main-network

    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql_server
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=${MSSQL_DB_PASSWORD}
        ports:
            - "${MSSQL_DB_PORT}:1433"
        volumes:
            - dbdata:/var/opt/mssql
            - ./data/mssql/:/var/opt/mssql/backup

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        tty: true
        ports:
            - '${REDIS_PORT}:6379'
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
        networks:
            - main-network


    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./data/esdata:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - main-network
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 5

    kibana:
        image: docker.elastic.co/kibana/kibana:8.15.0
        container_name: kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - "5601:5601"
        networks:
            - main-network
        depends_on:
            - elasticsearch   

    cassandra:
        image: cassandra:latest
        container_name: cassandra
        restart: unless-stopped
        ports:
            - "7000:7000"
        networks:
            - main-network
    
    typesense:
        image: typesense/typesense:26.0
        restart: on-failure
        ports:
            - "8108:8108"
        volumes:
            - ./data/typesense-data:/data
        command: '--data-dir /data --api-key=xyz --enable-cors'

# Networks
networks:
    main-network:
        name: main_network
        driver: bridge

# Volumes
volumes:
    dbdata:
        driver: local
